// <auto-generated />
namespace GroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedbfolder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedbfolder));
        
        string IMigrationMetadata.Id
        {
            get { return "202101120907074_change db folder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
