// <auto-generated />
namespace GroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class discountregex2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(discountregex2));
        
        string IMigrationMetadata.Id
        {
            get { return "202101221641394_discount regex2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
