// <auto-generated />
namespace GroupProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cartrating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartrating));
        
        string IMigrationMetadata.Id
        {
            get { return "202101150824276_cart-rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
